### PR TITLE
Add Leaflet Map at /districtmap

### PR DESCRIPTION
**Pull request by chriswhong**
Adds a map at /districtmap

I was not sure how to add a menu item to the header, as base.html is in councilmatic-core.... not sure how to extend it.

### CODE REVIEW

**Comment by cathydeng** [comment]
hey @chriswhong!

so for the map, I think we should
- use geojson from ocd, so that all the data is in the same place
- have all the map stuff live in django-councilmatic, with some settings (lat long, zoom, perhaps look & feel) in `local_settings.py` in nyc-councilmatic
- keep the table even if we have a map, so that ppl can do ctrl+f on a council member's name

I'll make some changes in django-councilmatic:
- add geography to the data model for council member posts, and load geojson from ocd (so that we don't have to do anything hacky to link up ppl & geographies)
- set up the council member template & map partial

after that, could you move all this awesome map & search stuff into django-councilmatic?

**Comment by chriswhong** [comment]
All sounds good, my head was wrapped around having a single
FeatureCollection, but no reason why we can't add features to the map
separately.

You would put the map on the existing council members page, or make it its
own page?  If I ctrl-F, I can't see the map anymore, and the list and the
map aren't linked, so I don't see the benefit.  Maybe shrinking down the
list and putting it beside the map could work, then we cna get rid of the
info window and just highlight the councilperson on the "mini list".  Just
a thought.

Last question, is there a less hacky way to get data from the model into
javascript?  I did var x = {somekey:{%somevalfromthemodel%}}.  Seems hacky,
but it worked.

**Comment by cathydeng** [comment]
the map should go on the same page. agree that it's awk if the page is long; I like the idea of shrinking down the list and putting it beside the map. we can move that info section to the bottom, and just keep one sentence of context at the top, e.g. something like 'NYC has 51 districts represented by council members'

& yeah, I can add the geography directly to the data model for the posts (posts being positions like district 1 rep, district 2 rep; posts are filled by people). posts are what we use to populate the content on the council members page (https://github.com/datamade/django-councilmatic/blob/fdba9e99667bc2784e44f760477b658c83284e40/councilmatic_core/templates/councilmatic_core/council_members.html#L26) & I'll make it so that you can access the geo json directly via `{{ post.geo_json }}`

**Comment by chriswhong** [comment]
All sounds great!  Let me know how I can help once all the bits are
rearranged.

-C

**Comment by derekeder** [comment]
hey @chriswhong we ended up doing this feature a slightly different way with the boundaries coming from Open Civic Data. We just pushed it up to the live site: http://nyc.councilmatic.org/council-members/

screen shot 2016-01-07 at 10 27 47 pm

Maps on the Council Member detail pages coming soon too! https://github.com/datamade/django-councilmatic/issues/17

After that, we'll get the address lookup working. 

Thanks so much for working on this and pushing to get this feature added. Its a great addition!

**Comment by chriswhong** [comment]
Sweet!  Looking good.

**Pull request closed without merging**
